[CmdletBinding()]
param(
    [string]$JavaRoot = 'D:\scenic-guide\ai'
)

$ErrorActionPreference = 'Stop'
$Example = Join-Path $JavaRoot '.env.example'
$Target = Join-Path $JavaRoot '.env'

if (-not (Test-Path -LiteralPath $Example)) {
    throw ("Canonical environment template is missing: {0}" -f $Example)
}

function New-LocalSecret {
    param([int]$Bytes = 48)
    $buffer = New-Object byte[] $Bytes
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($buffer) } finally { $rng.Dispose() }
    return [Convert]::ToBase64String($buffer)
}

function Is-PlaceholderSecret {
    param([string]$Value)
    $normalized = ([string]$Value).Trim()
    return [string]::IsNullOrWhiteSpace($normalized) -or $normalized -match '^(?:CHANGE_ME|your_|replace_)'
}

function Get-SecretEntryIndexes {
    param(
        [string[]]$Lines,
        [string]$Name
    )
    $indexes = @()
    for ($index = 0; $index -lt $Lines.Count; $index++) {
        $match = [regex]::Match($Lines[$index].Trim(), ('^(?:export\s+)?' + [regex]::Escape($Name) + '\s*=\s*(.*)$'))
        if ($match.Success) {
            $indexes += [pscustomobject]@{ Index = $index; Value = $match.Groups[1].Value.Trim() }
        }
    }
    return $indexes
}

function Ensure-ExistingSecret {
    param(
        [System.Collections.Generic.List[string]]$Lines,
        [string]$Name
    )
    $entries = @(Get-SecretEntryIndexes -Lines $Lines -Name $Name)
    $realEntry = $entries | Where-Object { -not (Is-PlaceholderSecret -Value $_.Value) } | Select-Object -First 1
    if ($null -ne $realEntry) {
        return $false
    }

    $secret = New-LocalSecret
    if ($entries.Count -eq 0) {
        [void]$Lines.Add("$Name=$secret")
    } else {
        # CHANGE_ME/empty entries are placeholders, not existing credentials.
        # Replace only those placeholders; never rotate a real value.
        foreach ($entry in $entries) {
            if (Is-PlaceholderSecret -Value $entry.Value) {
                $Lines[$entry.Index] = "$Name=$secret"
            }
        }
    }
    return $true
}

if (-not (Test-Path -LiteralPath $Target)) {
    $jwt = New-LocalSecret
    $auth = New-LocalSecret
    while ($jwt -eq $auth) { $auth = New-LocalSecret }

    # Keep a newly-created real file intentionally small. Optional provider,
    # legacy alias, and production-only values remain in .env.example only.
    $content = @"
# Canonical local runtime file. Generated by init-local-config.ps1.
# Optional features stay disabled until explicitly configured.
JWT_SECRET=$jwt
YUYOUZHICE_AUTH_SECRET=$auth
CORE_BACKEND_URL=http://127.0.0.1:8080
YUYOUZHICE_JAVA_TIMEOUT_MS=4000
KNOWLEDGE_DB_TYPE=sqlite
JWT_REVOCATION_REDIS_ENABLED=false
YUYOUZHICE_REVOKE_STORE=memory
ADMIN_BOOTSTRAP_MODE=disabled
PORT=3000
"@
    [System.IO.File]::WriteAllText($Target, $content.TrimStart(), [System.Text.UTF8Encoding]::new($false))
    Write-Host 'Created canonical local configuration (optional features remain disabled).'
    Write-Host 'JWT_SECRET = PRESENT'
    Write-Host 'YUYOUZHICE_AUTH_SECRET = PRESENT'
    exit 0
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.AddRange([System.IO.File]::ReadAllLines($Target))
$jwtChanged = Ensure-ExistingSecret -Lines $lines -Name 'JWT_SECRET'
$authChanged = Ensure-ExistingSecret -Lines $lines -Name 'YUYOUZHICE_AUTH_SECRET'
if ($jwtChanged -or $authChanged) {
    [System.IO.File]::WriteAllLines($Target, $lines.ToArray(), [System.Text.UTF8Encoding]::new($false))
}

Write-Host 'Canonical local configuration checked (real values were preserved).'
Write-Host 'JWT_SECRET = PRESENT'
Write-Host 'YUYOUZHICE_AUTH_SECRET = PRESENT'
